services:

  web:
    build: .

    container_name: hyrule_web

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn hyrule.wsgi:application --bind 0.0.0.0:8000
      "

    ports:
      - "8000:8000"

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped